# Generated by Django 4.0.4 on 2022-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='notification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
