# Generated by Django 4.0.4 on 2022-05-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_bid_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
