# Generated by Django 4.0.4 on 2022-05-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='highest_bid',
        ),
    ]
