# Generated by Django 4.0.4 on 2022-05-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_item_id_bid_item_remove_item_seller_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
