# Generated by Django 4.0.4 on 2022-05-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=9999)),
                ('item_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
