# Generated by Django 4.0.4 on 2022-05-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itemcategory_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='notification',
        ),
    ]
