# Generated by Django 4.0.4 on 2022-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_bid_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(default='pending', max_length=9999),
        ),
    ]
