# Generated by Django 4.0.4 on 2022-05-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
