# Generated by Django 4.0.4 on 2022-05-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(blank=True, max_length=9999)),
                ('cardnumber', models.CharField(blank=True, max_length=255)),
                ('expiration_date', models.CharField(blank=True, max_length=9999)),
                ('cvc', models.CharField(blank=True, max_length=9999)),
                ('payment_date', models.CharField(blank=True, max_length=9999)),
                ('total_amount', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=9999)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('street_name', models.CharField(blank=True, max_length=9999)),
                ('house_number', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=9999)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=9999)),
            ],
        ),
    ]
