# Generated by Django 4.0.4 on 2022-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='house_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='method',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='postal_code',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='street_name',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
