# Generated by Django 4.0.4 on 2022-05-12 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itemcategory_alter_item_category'),
        ('checkout', '0003_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='payment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.payment'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
