# Generated by Django 4.0.4 on 2022-05-12 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0006_alter_rating_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('street_name', models.CharField(default='', max_length=9999)),
                ('house_number', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=9999)),
                ('city', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=9999)),
                ('cardholder_name', models.CharField(default='', max_length=9999)),
                ('cardnumber', models.CharField(default='', max_length=255)),
                ('expiration_date', models.CharField(default='', max_length=9999)),
                ('cvc', models.CharField(default='', max_length=9999)),
                ('payment_date', models.CharField(default='', max_length=9999)),
                ('total_amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
