# Generated by Django 4.0.4 on 2022-05-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_bid_notification'),
        ('checkout', '0007_checkout_remove_shipping_payment_delete_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
