# Generated by Django 4.0.4 on 2022-05-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_checkout_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='total_amount',
        ),
    ]
