# Generated by Django 4.0.4 on 2022-05-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_checkout_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=9999)),
                ('checkout', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
            ],
        ),
    ]
