# Generated by Django 4.0.4 on 2022-05-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='checkout',
        ),
    ]
