# Generated by Django 4.0.4 on 2022-05-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_countries_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
        migrations.AddField(
            model_name='checkout',
            name='country_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.countries'),
        ),
    ]
