# Generated by Django 4.0.4 on 2022-05-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_remove_checkout_country_checkout_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='country_id',
            new_name='country',
        ),
    ]
