# Generated by Django 4.0.4 on 2022-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireSaleAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FireSale',
        ),
        migrations.DeleteModel(
            name='FireSaleCategory',
        ),
    ]
