# Generated by Django 4.0.4 on 2022-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0002_firesaleabout_delete_firesale_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FireSaleAbout',
            new_name='About',
        ),
    ]
