# Generated by Django 4.0.4 on 2022-05-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_item_id_bid_item_remove_item_seller_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_rename_userprofile_profile_rename_useruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
